name: Deploy HTML code on Amazon S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
	
    steps:
      - uses: actions/checkout@master
      - name: Configure AWS Credentials
		uses: aws-actions/configure-aws-credentials@master
        with:
		  	args: aws s3 sync . s3://$BUCKET_NAME --exclude '.git*/*'
		env:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
		  BUCKET_NAME: my-bucket-sampl