on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Install AWS CLI
    run:
        sudo apt-get update
        sudo apt-get install awscli -y
    
      - name: Deploy to s3
    run:
        aws s3 sync . s3://deploy-sample-bucket --delete
        
      env:
          aws-access-key-id:${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:${{ secrets.AWS_SECRET_ACCESS_KEY }}